# Generated by Django 3.2 on 2022-03-28 18:24

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('store_locator', django_countries.fields.CountryField(max_length=2)),
                ('designer', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['store_locator'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to='auth.user')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Woman', 'Woman'), ('Man', 'Man'), ('Other', 'Other')], max_length=6)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_phone', models.CharField(max_length=11)),
                ('date', models.DateField(max_length=10, validators=[django.core.validators.MinValueValidator(datetime.date.today)])),
                ('time', models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=5)),
                ('covid_safe', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=6)),
                ('slug', models.SlugField(max_length=250)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.location')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
