# Generated by Django 3.2 on 2022-03-28 18:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20220328_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='country',
            field=django_countries.fields.CountryField(default='', max_length=2),
            preserve_default=False,
        ),
    ]
