# Generated by Django 3.2 on 2022-04-02 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_auto_20220329_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('designer', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['designer'],
            },
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='appointment',
            name='designer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='design.designer'),
        ),
    ]
