# Generated by Django 3.2 on 2022-04-05 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0003_auto_20220402_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='slug',
        ),
    ]
