# Generated by Django 3.2 on 2022-04-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0004_auto_20220405_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], max_length=5, verbose_name='Please choose a time'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='designer',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Please choose a designer'),
        ),
    ]
