# Generated by Django 3.2 on 2022-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0005_auto_20220410_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00')], help_text='Choose a time', max_length=5),
        ),
        migrations.AlterField(
            model_name='designer',
            name='designer',
            field=models.CharField(help_text='Choose a designer', max_length=30, primary_key=True, serialize=False),
        ),
    ]
