# Generated by Django 3.2 on 2022-04-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0006_auto_20220410_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='designer',
            field=models.ForeignKey(help_text='Choose a designer', null=True, on_delete=django.db.models.deletion.CASCADE, to='design.designer'),
        ),
        migrations.AlterField(
            model_name='designer',
            name='designer',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
