# Generated by Django 3.2 on 2022-03-29 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('website_name', models.CharField(blank=True, max_length=254, null=True)),
                ('category2', models.IntegerField(blank=True, default=0, null=True)),
                ('category_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('category_image_url', models.URLField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category2', models.IntegerField(blank=True, default=0, null=True)),
                ('sku', models.CharField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('width', models.CharField(blank=True, max_length=254, null=True)),
                ('height', models.CharField(blank=True, max_length=254, null=True)),
                ('depth', models.CharField(blank=True, max_length=254, null=True)),
                ('sale', models.IntegerField(blank=True, default=0, verbose_name='85')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('wishlists', models.ManyToManyField(blank=True, default=None, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
