# Generated by Django 3.2 on 2022-03-16 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220316_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
