# Generated by Django 3.2 on 2022-03-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_category_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
