# Generated by Django 3.2 on 2022-04-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220402_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category2',
            field=models.CharField(blank=True, default=0, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='products.category'),
        ),
    ]
