# Generated by Django 3.2 on 2022-04-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20220402_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sale',
            new_name='sale_discount',
        ),
    ]
