# Generated by Django 3.2 on 2022-04-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_sale_product_sale_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
