# Generated by Django 3.2 on 2022-04-02 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_category_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
