# Generated by Django 3.2 on 2022-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_wishlist',
            field=models.CharField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
