# Generated by Django 3.2 on 2022-04-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_sale_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.CharField(blank=True, choices=[('sale', 'sale'), ('new_arrivals', 'new_arrivals')], max_length=254, null=True),
        ),
    ]
