# Generated by Django 3.2 on 2022-03-28 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0010_product_user_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_wishlist',
        ),
        migrations.AddField(
            model_name='product',
            name='user_wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
