# Generated by Django 3.2 on 2022-04-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_alter_product_category2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_discount',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
