# Generated by Django 3.2 on 2022-03-28 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220328_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user', models.CharField(default=0, max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.user'),
            preserve_default=False,
        ),
    ]
