# Generated by Django 3.2 on 2022-04-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20220405_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='current_price',
            new_name='currentprice',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sale_discount',
        ),
    ]
