# Generated by Django 3.2 on 2022-04-06 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0013_auto_20220405_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wishlists',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
