# Generated by Django 3.2 on 2022-04-06 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_product_wishlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlists',
            field=models.ManyToManyField(blank=True, default=None, related_name='wishlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
