# Generated by Django 3.2 on 2022-04-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_wishlists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.CharField(blank=True, choices=[('sale', 'sale'), ('new_arrivals', 'new_arrivals')], help_text='Please choose an option if this item is on sale or a new arrival', max_length=254, null=True),
        ),
    ]
