# Generated by Django 3.2 on 2022-04-25 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_category2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Please choose an option from this list except for 'Sale' or 'New Arrivals'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
    ]
