# Generated by Django 3.2 on 2023-04-16 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, help_text="Please choose                                  an option from this list except for                                  'Sale' or 'New Arrivals'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category2',
            field=models.CharField(blank=True, choices=[('sale', 'sale'), ('new_arrivals', 'new_arrivals')], help_text='Please choose                                  an option if this item is on sale or a                                  new arrival', max_length=254, null=True),
        ),
    ]
